const videoPath = (fileName) => `/videos/${fileName}`;

const CASE_DOMAINS = [
  {
    id: "large-models",
    number: "01",
    title: "大模型",
    english: "LARGE MODELS",
    icon: "cube",
    portal: { x: 59.5, y: 23 },
    video: videoPath("cases/01-large-models.mp4"),
    fileName: "cases/01-large-models.mp4",
  },
  {
    id: "research-institutes",
    number: "02",
    title: "科研院所",
    english: "SCIENTIFIC RESEARCH INSTITUTES",
    icon: "research",
    portal: { x: 20, y: 28 },
    video: videoPath("cases/02-research-institutes.mp4"),
    fileName: "cases/02-research-institutes.mp4",
  },
  {
    id: "high-end-manufacturing",
    number: "03",
    title: "高端制造",
    english: "HIGH-END MANUFACTURING",
    icon: "factory",
    portal: { x: 70.5, y: 40 },
    video: videoPath("cases/03-high-end-manufacturing.mp4"),
    fileName: "cases/03-high-end-manufacturing.mp4",
  },
  {
    id: "ocean-simulation",
    number: "04",
    title: "海洋模拟",
    english: "OCEAN SIMULATION",
    icon: "waves",
    portal: { x: 83, y: 52.5 },
    video: videoPath("cases/04-ocean-simulation.mp4"),
    fileName: "cases/04-ocean-simulation.mp4",
  },
  {
    id: "internet",
    number: "05",
    title: "互联网",
    english: "INTERNET",
    icon: "internet",
    portal: { x: 12, y: 63.5 },
    video: videoPath("cases/05-internet.mp4"),
    fileName: "cases/05-internet.mp4",
  },
  {
    id: "aerospace",
    number: "06",
    title: "航空航天",
    english: "AEROSPACE",
    icon: "rocket",
    portal: { x: 39, y: 75.5 },
    video: videoPath("cases/06-aerospace.mp4"),
    fileName: "cases/06-aerospace.mp4",
  },
  {
    id: "ai-for-science",
    number: "07",
    title: "AI 科学计算",
    english: "AI FOR SCIENCE",
    icon: "atom",
    englishLead: true,
    portal: { x: 58, y: 65 },
    video: videoPath("cases/07-ai-for-science.mp4"),
    fileName: "cases/07-ai-for-science.mp4",
  },
];

const productVideoPath = (number) => `products/${number}-product-film.mp4`;

const PRODUCT_DOMAINS = [
  {
    id: "product-01",
    number: "01",
    marker: "PRODUCT-01",
    title: "国产 Token 优化工厂",
    labelTitle: "国产Token优化工厂",
    english: "DOMESTIC TOKEN OPTIMIZATION FACTORY",
    icon: "diamond",
    orbitKey: "large-models",
    portal: { x: 52.75, y: 29.81 },
    sourceMedia: ["是石科技国产Token优化工厂产品介绍.mp4"],
  },
  {
    id: "product-02",
    number: "02",
    marker: "PRODUCT-02",
    title: "超智算集群",
    english: "SUPERINTELLIGENT COMPUTING CLUSTER",
    icon: "dots",
    orbitKey: "research-institutes",
    portal: { x: 21.95, y: 34.07 },
    sourceMedia: ["是石科技超智算集群介绍.mp4"],
  },
  {
    id: "product-03",
    number: "03",
    marker: "PRODUCT-03",
    title: "国产异构超智算中心",
    english: "DOMESTIC HETEROGENEOUS AI COMPUTING CENTER",
    icon: "package",
    orbitKey: "high-end-manufacturing",
    portal: { x: 59.82, y: 41.5 },
    sourceMedia: [
      "国产异构超智算中心 第1集.mp4",
      "AI为什么需要记忆 第2集.mp4",
      "芯片之间怎么秒传数据 第3集.mp4",
    ],
  },
  {
    id: "product-04",
    number: "04",
    marker: "PRODUCT-04",
    title: "国产 Token 优化工厂计算速度大比拼：CPU vs GPU",
    labelTitle: "CPU vs GPU 速度比拼",
    english: "CPU VS GPU PERFORMANCE",
    icon: "circles",
    orbitKey: "ocean-simulation",
    portal: { x: 69.24, y: 55.18 },
    sourceMedia: ["Token优化工厂-CPU国产移植GPU1080P.mp4"],
  },
  {
    id: "product-05",
    number: "05",
    marker: "PRODUCT-05",
    title: "国产 Token 优化工厂－技术优势",
    labelTitle: "Token优化工厂技术优势",
    english: "TOKEN FACTORY ADVANTAGES",
    icon: "polygon",
    orbitKey: "internet",
    portal: { x: 13.85, y: 58.87 },
    sourceMedia: ["是石科技国产Token优化工厂产品优势盘点.mp4"],
  },
  {
    id: "product-06",
    number: "06",
    marker: "PRODUCT-06",
    title: "AI Infra",
    english: "AI INFRASTRUCTURE",
    icon: "stack",
    orbitKey: "aerospace",
    portal: { x: 27.49, y: 68.68 },
    sourceMedia: ["AIinfra.mp4"],
  },
  {
    id: "product-07",
    number: "07",
    marker: "PRODUCT-07",
    title: "PD 分离",
    english: "PD DISAGGREGATION",
    icon: "transparent-cube",
    orbitKey: "ai-for-science",
    portal: { x: 48.25, y: 61.31 },
    sourceMedia: ["AI动画-PD分离.mp4"],
  },
  {
    id: "product-08",
    number: "08",
    marker: "PRODUCT-08",
    title: "投机解码",
    english: "SPECULATIVE DECODING",
    icon: "cube",
    orbitKey: "aerospace",
    portal: { x: 27.49, y: 27.32 },
    sourceMedia: ["投机解码.mp4"],
  },
  {
    id: "product-09",
    number: "09",
    marker: "PRODUCT-09",
    title: "多层级 KV Cache",
    english: "MULTI-LEVEL KV CACHE",
    icon: "atom",
    orbitKey: "high-end-manufacturing",
    portal: { x: 55.83, y: 57.89 },
    sourceMedia: ["KVCache.mp4"],
  },
].map((product) => ({
  ...product,
  mediaCount: product.sourceMedia.length,
  video: videoPath(productVideoPath(product.number)),
  fileName: productVideoPath(product.number),
  placeholder: false,
}));

export const CONTENT_CATALOGS = [
  {
    id: "success-cases",
    number: "01",
    title: "成果案例",
    english: "SUCCESS CASES",
    status: "07 CASES · INTERACTIVE VIDEO",
    itemNoun: "案例",
    items: CASE_DOMAINS,
  },
  {
    id: "product-introduction",
    number: "02",
    title: "产品介绍",
    english: "PRODUCT INTRODUCTION",
    status: "09 PRODUCTS · 11 SOURCE FILMS",
    itemNoun: "产品",
    items: PRODUCT_DOMAINS,
  },
];

export const DEFAULT_CATALOG_ID = CONTENT_CATALOGS[0].id;
export const DOMAINS = CASE_DOMAINS;
export const DEMO_DURATION = 225;
